#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Package
          command: |
            bash ./package.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: target/lambda.zip
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Plan
          command: |
            terraform init
            terraform plan -var build_no=${CIRCLE_BUILD_NUM}
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Apply
          command: |
            terraform init
            terraform apply -var build_no=${CIRCLE_BUILD_NUM} -auto-approve

workflows:
  version: 2
  apply:
    jobs:
      - build
      - plan:
          requires:
            - build
      # - approval:
      #     type: approval
      #     requires:
      #       - plan
      - apply:
          requires:
            - plan
