#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Package
          command: |
            ./package.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: target/lambda.zip
  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Plan
          command: |
            terraform init
            terraform plan
  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Apply
          command: |
            terraform init
            terraform apply -auto-approve

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - plan:
          requires:
            - build
      - apply:
          requires:
            - plan
